"""add survey

Revision ID: c62a7e34e513
Revises: 16ce4b1ae3b8
Create Date: 2024-05-26 16:25:19.217085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62a7e34e513'
down_revision = '16ce4b1ae3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('personal_use_1', sa.Integer(), nullable=False),
    sa.Column('professional_use_2', sa.Integer(), nullable=False),
    sa.Column('genAI_decisionmaking_3', sa.Integer(), nullable=False),
    sa.Column('trust_4', sa.Integer(), nullable=False),
    sa.Column('rationale_5', sa.Integer(), nullable=False),
    sa.Column('willingness_to_use_6', sa.Integer(), nullable=False),
    sa.Column('usefulness_7', sa.Integer(), nullable=False),
    sa.Column('disagree_8', sa.Text(), nullable=True),
    sa.Column('additional_9', sa.Text(), nullable=True),
    sa.Column('interview_consent_10', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey')
    # ### end Alembic commands ###
